export const gameEffects = [
    { id: "clear", name: "§cQuitar todos los efectos", basePrice: 0 },
    { id: "speed", name: "Velocidad", basePrice: 15 },
    { id: "slowness", name: "Lentitud", basePrice: 10 },
    { id: "haste", name: "Prisa Minera", basePrice: 15 },
    { id: "mining_fatigue", name: "Fatiga Minera", basePrice: 10 },
    { id: "strength", name: "Fuerza", basePrice: 50 },
    { id: "instant_health", name: "Salud Instantánea", basePrice: 30 },
    { id: "instant_damage", name: "Daño Instantáneo", basePrice: 10 },
    { id: "jump_boost", name: "Impulso de Salto", basePrice: 15 },
    { id: "nausea", name: "Náuseas", basePrice: 10 },
    { id: "regeneration", name: "Regeneración", basePrice: 50 },
    { id: "resistance", name: "Resistencia", basePrice: 25 },
    { id: "fire_resistance", name: "Resistencia al Fuego", basePrice: 25 },
    { id: "water_breathing", name: "Respiración Acuática", basePrice: 15 },
    { id: "invisibility", name: "Invisibilidad", basePrice: 15 },
    { id: "blindness", name: "Ceguera", basePrice: 10 },
    { id: "night_vision", name: "Visión Nocturna", basePrice: 15 },
    { id: "hunger", name: "Hambre", basePrice: 10 },
    { id: "weakness", name: "Debilidad", basePrice: 10 },
    { id: "poison", name: "Veneno", basePrice: 10 },
    { id: "wither", name: "Wither", basePrice: 10 },
    { id: "health_boost", name: "Impulso de Salud", basePrice: 50 },
    { id: "absorption", name: "Absorción", basePrice: 50 },
    { id: "saturation", name: "Saturación", basePrice: 50 },
    { id: "levitation", name: "Levitación", basePrice: 10 },
    { id: "fatal_poison", name: "Veneno Fatal", basePrice: 10 },
    { id: "conduit_power", name: "Poder del Canalizador", basePrice: 50 },
    { id: "slow_falling", name: "Caída Lenta", basePrice: 15 },
    { id: "bad_omen", name: "Mal Presagio", basePrice: 10 },
    { id: "hero_of_the_village", name: "Héroe de la Aldea", basePrice: 50 },
    { id: "darkness", name: "Oscuridad", basePrice: 10 }
];
