const itemCategories = {
    "Bloques naturales": [
        { id: "stone", name: "Piedra", price: 5 },
        { id: "cobblestone", name: "Adoquín", price: 5 },
        { id: "deepslate", name: "Pizarra Profunda", price: 8 },
        { id: "granite", name: "Granito", price: 10 },
        { id: "diorite", name: "Diorita", price: 10 },
        { id: "andesite", name: "Andesita", price: 10 },
        { id: "dirt", name: "Tierra", price: 5 },
        { id: "grass_block", name: "Césped", price: 25 },
        { id: "sand", name: "Arena", price: 5 },
        { id: "red_sand", name: "Arena Roja", price: 8 },
        { id: "gravel", name: "Grava", price: 5 },
        { id: "clay", name: "Arcilla", price: 15 },
        { id: "snow", name: "Nieve", price: 15 },
        { id: "ice", name: "Hielo", price: 50 },
        { id: "packed_ice", name: "Hielo Compacto", price: 150 },
        { id: "blue_ice", name: "Hielo Azul", price: 500 }
    ],
    "Minerales": [
        { id: "coal_ore", name: "Mineral de Carbón", price: 50 },
        { id: "iron_ore", name: "Mineral de Hierro", price: 150 },
        { id: "copper_ore", name: "Mineral de Cobre", price: 80 },
        { id: "gold_ore", name: "Mineral de Oro", price: 400 },
        { id: "redstone_ore", name: "Mineral de Redstone", price: 100 },
        { id: "lapis_ore", name: "Mineral de Lapis Lazuli", price: 150 },
        { id: "diamond_ore", name: "Mineral de Diamante", price: 3500 },
        { id: "emerald_ore", name: "Mineral de Esmeralda", price: 4000 },
        { id: "nether_gold_ore", name: "Oro del Nether", price: 200 },
        { id: "quartz_ore", name: "Cuarzo del Nether", price: 150 },
        { id: "ancient_debris", name: "Escombros Ancestrales", price: 25000 }
    ],
    "Bloques de madera": [
        { id: "oak_log", name: "Tronco de Roble", price: 20 },
        { id: "spruce_log", name: "Tronco de Abeto", price: 20 },
        { id: "birch_log", name: "Tronco de Abedul", price: 20 },
        { id: "jungle_log", name: "Tronco de Jungla", price: 20 },
        { id: "acacia_log", name: "Tronco de Acacia", price: 20 },
        { id: "dark_oak_log", name: "Tronco de Roble Oscuro", price: 20 },
        { id: "mangrove_log", name: "Tronco de Manglar", price: 20 },
        { id: "cherry_log", name: "Tronco de Cerezo", price: 20 },
        { id: "oak_planks", name: "Tablas de Roble", price: 8 },
        { id: "oak_stairs", name: "Escaleras de Roble", price: 12 },
        { id: "oak_slab", name: "Losa de Roble", price: 5 },
        { id: "oak_fence", name: "Valla de Roble", price: 10 },
        { id: "oak_door", name: "Puerta de Roble", price: 20 },
        { id: "oak_trapdoor", name: "Trampilla de Roble", price: 20 },
        { id: "oak_button", name: "Botón de Madera", price: 5 },
        { id: "oak_pressure_plate", name: "Placa de Presión", price: 10 }
    ],
    "Bloques del Nether": [
        { id: "netherrack", name: "Netherrack", price: 5 },
        { id: "basalt", name: "Basalto", price: 15 },
        { id: "blackstone", name: "Piedra Negra", price: 15 },
        { id: "soul_sand", name: "Arena de Almas", price: 50 },
        { id: "soul_soil", name: "Solo das Almas", price: 50 },
        { id: "magma", name: "Bloque de Magma", price: 60 },
        { id: "nether_bricks", name: "Ladrillos del Nether", price: 40 },
        { id: "red_nether_bricks", name: "Ladrillos Rojos", price: 60 },
        { id: "nether_wart_block", name: "Bloque de Verruga", price: 80 },
        { id: "shroomlight", name: "Hongo Luminoso", price: 250 }
    ],
    "Bloques del End": [
        { id: "end_stone", name: "Piedra del End", price: 25 },
        { id: "end_bricks", name: "Ladrillos del End", price: 50 },
        { id: "purpur_block", name: "Bloque de Púrpura", price: 100 },
        { id: "purpur_pillar", name: "Pilar de Púrpura", price: 120 },
        { id: "purpur_stairs", name: "Escaleras de Púrpura", price: 100 },
        { id: "end_rod", name: "Vara del End", price: 400 }
    ],
    "Bloques decorativos": [
        { id: "brick_block", name: "Ladrillos", price: 80 },
        { id: "stonebrick", name: "Ladrillos de Piedra", price: 20 },
        { id: "quartz_block", name: "Bloque de Cuarzo", price: 150 },
        { id: "terracotta", name: "Terracota", price: 40 },
        { id: "white_terracotta", name: "Terracota Blanca", price: 50 },
        { id: "concrete", name: "Concreto Blanco", price: 60 },
        { id: "concrete_powder", name: "Polvo de Concreto", price: 30 },
        { id: "glass", name: "Vidrio", price: 50 },
        { id: "white_stained_glass", name: "Vidrio Blanco", price: 60 }
    ],
    "Bloques funcionales": [
        { id: "crafting_table", name: "Mesa de Trabajo", price: 50 },
        { id: "furnace", name: "Horno", price: 50 },
        { id: "blast_furnace", name: "Alto Horno", price: 250 },
        { id: "smoker", name: "Ahumador", price: 250 },
        { id: "chest", name: "Cofre", price: 80 },
        { id: "trapped_chest", name: "Cofre Trampa", price: 150 },
        { id: "barrel", name: "Barril", price: 80 },
        { id: "anvil", name: "Yunque", price: 1200 },
        { id: "enchanting_table", name: "Mesa de Encantamiento", price: 15000 },
        { id: "grindstone", name: "Piedra de Afilar", price: 150 },
        { id: "smithing_table", name: "Mesa de Herrería", price: 300 },
        { id: "stonecutter", name: "Cortapiedras", price: 150 },
        { id: "lectern", name: "Atril", price: 400 }
    ],
    "Bloques de plantas": [
        { id: "wheat", name: "Trigo", price: 10 },
        { id: "carrot", name: "Zanahorias", price: 10 },
        { id: "potato", name: "Papas", price: 10 },
        { id: "sugar_cane", name: "Caña de Azúcar", price: 25 },
        { id: "bamboo", name: "Bambú", price: 25 },
        { id: "cactus", name: "Cactus", price: 40 },
        { id: "pumpkin", name: "Calabaza", price: 100 },
        { id: "melon_block", name: "Melón", price: 100 },
        { id: "poppy", name: "Amapola", price: 50 },
        { id: "oak_leaves", name: "Hojas de Roble", price: 10 }
    ],
    "Armas": [
        { id: "wooden_sword", name: "Espada de Madera", price: 50 },
        { id: "stone_sword", name: "Espada de Piedra", price: 150 },
        { id: "iron_sword", name: "Espada de Hierro", price: 1200 },
        { id: "golden_sword", name: "Espada de Oro", price: 800 },
        { id: "diamond_sword", name: "Espada de Diamante", price: 9000 },
        { id: "netherite_sword", name: "Espada de Netherita", price: 50000 },
        { id: "bow", name: "Arco", price: 1200 },
        { id: "crossbow", name: "Ballesta", price: 2500 },
        { id: "trident", name: "Tridente", price: 150000 }
    ],
    "Herramientas": [
        { id: "wooden_pickaxe", name: "Pico de Madera", price: 80 },
        { id: "stone_pickaxe", name: "Pico de Piedra", price: 250 },
        { id: "iron_pickaxe", name: "Pico de Hierro", price: 2000 },
        { id: "golden_pickaxe", name: "Pico de Oro", price: 1500 },
        { id: "diamond_pickaxe", name: "Pico de Diamante", price: 15000 },
        { id: "netherite_pickaxe", name: "Pico de Netherita", price: 80000 },
        { id: "wooden_axe", name: "Hacha de Madera", price: 80 },
        { id: "stone_axe", name: "Hacha de Piedra", price: 250 },
        { id: "iron_axe", name: "Hacha de Hierro", price: 2000 },
        { id: "golden_axe", name: "Hacha de Oro", price: 1500 },
        { id: "diamond_axe", name: "Hacha de Diamante", price: 15000 },
        { id: "netherite_axe", name: "Hacha de Netherita", price: 80000 },
        { id: "wooden_shovel", name: "Pala de Madera", price: 40 },
        { id: "stone_shovel", name: "Pala de Piedra", price: 100 },
        { id: "iron_shovel", name: "Pala de Hierro", price: 800 },
        { id: "golden_shovel", name: "Pala de Oro", price: 600 },
        { id: "diamond_shovel", name: "Pala de Diamante", price: 6000 },
        { id: "netherite_shovel", name: "Pala de Netherita", price: 30000 },
        { id: "wooden_hoe", name: "Azada de Madera", price: 40 },
        { id: "stone_hoe", name: "Azada de Piedra", price: 100 },
        { id: "iron_hoe", name: "Azada de Hierro", price: 800 },
        { id: "golden_hoe", name: "Azada de Oro", price: 600 },
        { id: "diamond_hoe", name: "Azada de Diamante", price: 6000 },
        { id: "netherite_hoe", name: "Azada de Netherita", price: 30000 },
        { id: "shears", name: "Tijeras", price: 300 },
        { id: "fishing_rod", name: "Caña de Pescar", price: 400 },
        { id: "flint_and_steel", name: "Mechero", price: 250 },
        { id: "compass", name: "Brújula", price: 1200 },
        { id: "clock", name: "Reloj", price: 1500 }
    ],
    "Armaduras": [
        { id: "leather_helmet", name: "Casco de Cuero", price: 200 },
        { id: "leather_chestplate", name: "Pechera de Cuero", price: 400 },
        { id: "leather_leggings", name: "Pantalones de Cuero", price: 350 },
        { id: "leather_boots", name: "Botas de Cuero", price: 150 },
        { id: "iron_helmet", name: "Casco de Hierro", price: 2500 },
        { id: "iron_chestplate", name: "Pechera de Hierro", price: 5000 },
        { id: "iron_leggings", name: "Pantalones de Hierro", price: 4500 },
        { id: "iron_boots", name: "Botas de Hierro", price: 1500 },
        { id: "golden_helmet", name: "Casco de Oro", price: 1500 },
        { id: "golden_chestplate", name: "Pechera de Oro", price: 3000 },
        { id: "golden_leggings", name: "Pantalones de Oro", price: 2500 },
        { id: "golden_boots", name: "Botas de Oro", price: 1000 },
        { id: "diamond_helmet", name: "Casco de Diamante", price: 15000 },
        { id: "diamond_chestplate", name: "Pechera de Diamante", price: 30000 },
        { id: "diamond_leggings", name: "Pantalones de Diamante", price: 25000 },
        { id: "diamond_boots", name: "Botas de Diamante", price: 10000 },
        { id: "netherite_helmet", name: "Casco de Netherita", price: 100000 },
        { id: "netherite_chestplate", name: "Pechera de Netherita", price: 200000 },
        { id: "netherite_leggings", name: "Pantalones de Netherita", price: 180000 },
        { id: "netherite_boots", name: "Botas de Netherita", price: 80000 },
        { id: "turtle_helmet", name: "Caparazón de Tortuga", price: 15000 },
        { id: "elytra", name: "Elytra", price: 500000 }
    ],
    "Munición": [
        { id: "arrow", name: "Flecha", price: 20 },
    ],
    "Comida": [
        { id: "apple", name: "Manzana", price: 40 },
        { id: "golden_apple", name: "Manzana Dorada", price: 5000 },
        { id: "enchanted_golden_apple", name: "Manzana Dorada Encantada", price: 150000 },
        { id: "bread", name: "Pan", price: 40 },
        { id: "porkchop", name: "Carne de Cerdo", price: 80 },
        { id: "cooked_porkchop", name: "Cerdo Cocinado", price: 120 },
        { id: "chicken", name: "Pollo", price: 80 },
        { id: "cooked_chicken", name: "Pollo Cocido", price: 120 },
        { id: "cod", name: "Pescado", price: 80 },
        { id: "salmon", name: "Salmón", price: 80 },
        { id: "tropical_fish", name: "Pescado Tropical", price: 250 },
        { id: "pufferfish", name: "Pez Globo", price: 400 },
        { id: "carrot", name: "Zanahoria", price: 40 },
        { id: "potato", name: "Papa", price: 40 },
        { id: "baked_potato", name: "Papa Horneada", price: 80 },
        { id: "poisonous_potato", name: "Papa Venenosa", price: 200 },
        { id: "beetroot", name: "Remolacha", price: 40 },
        { id: "beetroot_soup", name: "Sopa de Remolacha", price: 150 },
        { id: "mushroom_stew", name: "Sopa de Hongos", price: 150 },
        { id: "pumpkin_pie", name: "Pastel de Calabaza", price: 350 },
        { id: "cake", name: "Pastel", price: 600 },
        { id: "cookie", name: "Galleta", price: 40 },
        { id: "sweet_berries", name: "Bayas Dulces", price: 40 },
        { id: "chorus_fruit", name: "Fruta Chorus", price: 200 }
    ],
    "Pociones y alquimia": [
        { id: "glass_bottle", name: "Botella de Vidrio", price: 40 },
        { id: "spider_eye", name: "Ojo de Araña", price: 200 },
        { id: "fermented_spider_eye", name: "Ojo de Araña Fermentado", price: 500 },
        { id: "blaze_powder", name: "Polvo de Blaze", price: 1000 },
        { id: "blaze_rod", name: "Vara de Blaze", price: 2000 },
        { id: "ghast_tear", name: "Lágrima de Ghast", price: 8000 },
        { id: "magma_cream", name: "Crema de Magma", price: 1500 },
        { id: "redstone", name: "Polvo de Redstone", price: 50 },
        { id: "glowstone_dust", name: "Polvo de Glowstone", price: 80 }
    ],
    "Materiales": [
        { id: "stick", name: "Palo", price: 10 },
        { id: "leather", name: "Cuero", price: 100 },
        { id: "bone", name: "Hueso", price: 50 },
        { id: "string", name: "Hilo", price: 50 },
        { id: "feather", name: "Pluma", price: 50 },
        { id: "gunpowder", name: "Pólvora", price: 500 },
        { id: "ender_pearl", name: "Perla de Ender", price: 2500 },
        { id: "nether_star", name: "Nether Star", price: 2000000 },
        { id: "slime_ball", name: "Bola de Slime", price: 400 },
        { id: "clay_ball", name: "Bola de Arcilla", price: 20 },
        { id: "paper", name: "Papel", price: 40 },
        { id: "book", name: "Libro", price: 250 },
        { id: "writable_book", name: "Libro y Pluma", price: 600 },
        { id: "enchanted_book", name: "Libro Encantado", price: 8000 }
    ],
    "Objetos especiales": [
        { id: "empty_map", name: "Mapa Vacío", price: 1500 },
        { id: "map", name: "Mapa", price: 2500 },
        { id: "name_tag", name: "Etiqueta de Nombre", price: 8000 },
        { id: "saddle", name: "Montura", price: 15000 },
        { id: "totem_of_undying", name: "Totem de Inmortalidad", price: 150000 },
        { id: "music_disc_13", name: "Disco Musical", price: 50000 },
        { id: "firework_rocket", name: "Cohete de Fuegos Artificiales", price: 200 },
        { id: "firework_star", name: "Estrella de Fuegos Artificiales", price: 150 }
    ],
    "Bloques especiales": [
        { id: "command_block", name: "Bloque de Comandos", price: 100000 },
        { id: "chain_command_block", name: "Bloque de Comandos en Cadena", price: 100000 },
        { id: "repeating_command_block", name: "Bloque de Comandos Iterativo", price: 100000 },
        { id: "structure_block", name: "Bloque de Estructuras", price: 100000 },
        { id: "structure_void", name: "Vacío de Estructuras", price: 10000 },
        { id: "jigsaw", name: "Bloque Rompecabezas", price: 100000 },
        { id: "border_block", name: "Bloque de Borde", price: 100000 },
        { id: "allow", name: "Bloque Permitir", price: 100000 },
        { id: "deny", name: "Bloque Rechazar", price: 100000 },
        { id: "barrier", name: "Barrera", price: 100000 },
        { id: "light_block", name: "Bloque de Luz", price: 50000 }
    ],
    "Bloques de portales": [
        { id: "end_portal", name: "Bloque de Portal del End", price: 500000 },
        { id: "end_gateway", name: "Portal de Escape del End", price: 500000 }
    ],
    "Bloques técnicos": [
        { id: "bedrock", name: "Bedrock", price: 1000000 },
        { id: "mob_spawner", name: "Generador de Mobs", price: 5000000 },
        { id: "water", name: "Bloque de Agua", price: 10000 },
        { id: "lava", name: "Bloque de Lava", price: 10000 },
        { id: "fire", name: "Fuego", price: 5000 }
    ],
    "Ítems ocultos o técnicos": [
        { id: "camera", name: "Cámara", price: 50000 },
        { id: "spawn_egg 51", name: "Huevo NPC", price: 100000 },
        { id: "spawn_egg 56", name: "Huevo de Agente", price: 100000 }
    ]
};

export { itemCategories };
