import { world, system } from "@minecraft/server";

export const LANG = {
    es: {
        main_title: "§9[ §bMENU CDR §9]",
        stats_btn: "§9[ §bEstadísticas §9]",
        stats: "§9[ §bEstadísticas §9]",
        lang_btn: "§9[ §bIdiomas §9]",
        return_btn: "§c[ §6Regresar §c]",
        balance: "§9[ §bSaldo: §9] §a$",
        balance_cursed: "§9[ §bSaldo: §9] §5$",
        balance_blocked_msg: "(No puedes usar este saldo)",
        user_label: "§9[ §bUsuario: §9] §f",
        commands: "§9[ §bConsola §9]",
        tp: "§9[ §bTeletransporte §9]",
        tp_to: "§9[ §bTP §9]",
        tp_here: "§9[ §bTraer amigo §9]",
        tp_accept: "§9[ §bAceptar §9]",
        wp_go: "§9[ §bIr §9]",
        waypoint: "§9[ §bMarcadores §9]",
        shop: "§9[ §bTienda §9]",
        shop_title: "§9[ §bTienda §9]",
        effects: "§9[ §bEfectos §9]",
        items: "§9[ §bObjetos §9]",
        enchantments: "§9[ §bEncantamientos §9]",
        enchantments_title: "§9[ §bEncantamientos §9]",
        kits: "§9[ §bKits §9]",
        money: "§9[ §bEnviar Dinero §9]",
        money_sent: "§aLe enviaste dinero a: §b",
        money_cooldown: "§cDebes esperar 3 días de juego para enviar dinero maldecido de nuevo.",
        money_infected: "§c¡Has sido infectado por una maldición de §b",
        missions: "§9[ §bMisiones §9]",
        missions_title: "§9[ §bMisiones §9]",
        board_updated: "Tablero actualizado",
        missions_mult: "§bMultiplicador Misiones",
        mission_easy: "§9[ §bFácil §9]",
        mission_normal: "§9[ §bNormal §9]",
        mission_hard: "§9[ §bDifícil §9]",
        mission_hardcore: "§9[ §bHardcore §9]",
        mission_your: "Tu Misión",
        mission_task: "Tarea",
        mission_obj: "Objetivo",
        mission_prog: "Progreso",
        mission_reward: "Recompensa aprox",
        mission_renew: "Tablero renueva en",
        mission_accept: "§9[ §bAceptar Misión §9]",
        mission_cancel: "§9[ §bCancelar Misión §9]",
        mission_abandon: "§c[ §fAbandonar Fallida §c]",
        mission_active: "§aACTIVA",
        mission_failed: "§cFALLIDA",
        mission_days: "Días",
        mission_kill: "Matar",
        mission_mine: "Picar",
        nether: "§9[ §bNether §9]",
        end: "§9[ §bEnd §9]",
        admin: "§9[ §bAdministración §9]",
        credits: "§9[ §bCréditos §9]",
        stats_title: "§9[ §bEstadísticas §9]",
        sel_player: "§bElegir Jugador",
        stat_balance: "§9[ §bSaldo §9]",
        stat_kill: "§9[ §bBajas §9]",
        stat_deaths: "§9[ §bMuertes §9]",
        stat_mobs_passive: "§9[ §bMobs Pasivos §9]",
        stat_mobs_hostile: "§9[ §bMobs Hostiles §9]",
        stat_mobs_boss: "§9[ §bJefes §9]",
        stat_blocks: "§9[ §bBloques §9]",
        stat_mission_easy: "§9[ §bMisión Fácil §9]",
        stat_mission_normal: "§9[ §bMisión Normal §9]",
        stat_mission_hard: "§9[ §bMisión Difícil §9]",
        stat_mission_hardcore: "§9[ §bMisión Hardcore §9]",
        stat_days: "§9[ §bDías Jugados §9]",
        stat_hours: "§9[ §bTiempo Jugado §9]",
        lang_title: "§9[ §bElegir Idioma §9]",
        lang_es: "§bEspañol",
        lang_en: "§bEnglish",
        lang_pt: "§bPortuguês",
        confirm: "§bConfirmar",
        cancel: "§bCancelar",
        success: "§aÉxito",
        error: "§cNo puedes utilizar esto ahorita",
        dimension_blocked_msg: "§cNo tienes permitido ir a esta dimensión.",
        kit_iron: "§bKit Hierro",
        kit_diamond: "§bKit Diamante",
        kit_netherite: "§bKit Netherite",
        moderation_title: "§9[ §bModeración §9]",
        vis_btn: "§9[ §bVisibilidad §9]",
        order_btn: "§9[ §bOrdenar §9]",
        diff_btn: "§9[ §bDificuldade §9]",
        gm_btn: "§9[ §bModo Juego §9]",
        econ_btn: "§9[ §bEconomía §9]",
        prices_btn: "§9[ §bPrecios §9]",
        buy_btn: "§9[ §bDar dinero §9]",
        sell_btn: "§9[ §bRemover dinero §9]",
        remove_curse_btn: "§9[ §bRemover Maldición §9]",
        add_curse_btn: "§9[ §bAñadir Maldición §9]",
        victim_label: "§bElegir Víctima",
        guilty_label: "§bElegir Culpable",
        cursed: "§5[ §dMaldecido §5]",
        price_control_title: "§9[ §bControl de Precios §9]",
        price_mult_hint: "Mult. (Ej: 1.0)",
        rew_passive: "§bRecompensa Pasivos",
        rew_hostile: "§bRecompensa Hostiles",
        rew_boss: "§bRecompensa Jefes",
        pos_label: "Posición",
        config_saved: "Configuración guardada",
        order_saved: "Orden guardado",
        edit_player: "Editar Jugador",
        vis_global_desc: "Ocultar Global",
        perm_updated: "Permisos actualizados",
        all_players: "Todos (@a)",
        money_add: "Dar Dinero",
        money_remove: "Quitar Dinero",
        diff_p: "§a[ §bPacífico §a]",
        diff_e: "§e[ §bFácil §e]",
        diff_n: "§6[ §bNormal §6]",
        diff_h: "§c[ §bDifícil §c]",
        gm_s: "§b[ §bSupervivencia §b]",
        gm_c: "§b[ §bCreativo §b]",
        gm_a: "§b[ §bAventura §b]",
        gm_sp: "§b[ §bEspectador §b]",
        wp_create_desc: "Escribe nombre:",
        wp_saved_msg: "Marcador guardado",
        admin_msg: "§aAdmin Asignado",
        no_players: "Sin jugadores",
        limit_reached: "Límite alcanzado",
        helper_btn: "§9[ §bAyudante §9]",
        rank_mgmt_btn: "§9[ §bGestión de Rangos §9]",
        rank_sel: "Seleccionar Rango",
        rank_admin: "Administrador (Control total)",
        rank_helper: "Ayudante (Moderación básica)",
        rank_none: "Quitar Rango",
        rank_confirm_title: "Confirmar Rango",
        rank_confirm_body: "¿Estás seguro?",
        rank_desc_admin: "Acceso total a comandos y economía.",
        rank_desc_helper: "Acceso a moderación básica.",
        rank_desc_none: "Sin privilegios.",
        rank_desc_cdr: "PROPIETARIO (CDR). Control absoluto.",
        wp_infinite: "Marcadores Infinitos",
        test_mode_title: "§9[ §bPanel de Pruebas §9]",
        test_mode_player: "§bProbar como Jugador",
        test_mode_helper: "§bProbar como Ayudante",
        test_mode_admin: "§bProbar como Administrador",
        test_mode_reset: "§cDesactivar modos",
        test_mode_on: "Modo Pruebas activado.",
        test_mode_off: "Modo Pruebas desactivado.",
        test_mode_helper_active: "Modo Prueba: AYUDANTE activado.",
        test_mode_admin_active: "Modo Prueba: ADMINISTRADOR activado.",
        only_one_at_time: "1 solo por vez",
        credits_body: "§8§l»-----------------------«\n§9§l   SISTEMAS CDR v2.0\n§8§l»-----------------------«\n§bCreado por:\n§f- §6ARSENIC 2007 §7(Dev)\n§f- §eREYES200705 §7(UI)\n\n§bModulos:\n§f- §7Menu Engine\n§f- §7Rank Manager\n\n§8§l»-----------------------«\n§7 Gracias por tu confianza\n§8§l»-----------------------«",
        active: "Activa",
        busy: "Ocupado",
        warning_curse_clear: "¡ADVERTENCIA! Al completar cualquiera se limpiará tu maldición.",
        progreso_actualizado: "Progreso actualizado",
        maldicion_removida: "¡Maldición removida!",
        mission_title_cursed: "§9[ §5SISTEMA MALDECIDO §9]",
        mission_label: "Misión",
        admin_control_label: "(CDR/ADM/HELP)",
        ow_short: "SB", net_short: "NET", end_short: "END",
        engine_loaded: "Menu Engine v1.0 - §aCARGADO",
        perm_target_msg: "Tus permisos han sido actualizados.",
        // Enchantments
        protection: "Protección",
        fire_protection: "Protección contra el Fuego",
        feather_falling: "Caída de Pluma",
        blast_protection: "Protección contra Explosiones",
        projectile_protection: "Protección contra Proyectiles",
        respiration: "Respiración",
        aqua_affinity: "Afinidad al Agua",
        thorns: "Espinas",
        depth_strider: "Agilidad Acuática",
        frost_walker: "Paso Helado",
        soul_speed: "Velocidad de Almas",
        swift_sneak: "Sigilo Veloz",
        sharpness: "Filo",
        smite: "Golpeo",
        bane_of_arthropods: "Perdición de los Artrópodos",
        knockback: "Empuje",
        fire_aspect: "Aspecto Ígneo",
        looting: "Saqueo",
        efficiency: "Eficiencia",
        silk_touch: "Toque de Seda",
        unbreaking: "Irrompibilidad",
        fortune: "Fortuna",
        power: "Poder",
        punch: "Retroceso",
        flame: "Llama",
        infinity: "Infinidad",
        luck_of_the_sea: "Suerte Marina",
        lure: "Atracción",
        loyalty: "Lealtad",
        impaling: "Empalamiento",
        riptide: "Propulsión Acuática",
        channeling: "Canalización",
        multishot: "Multidisparo",
        piercing: "Perforación",
        quick_charge: "Carga Rápida",
        mending: "Reparación",
        curse_of_binding: "Maldición de Ligamiento",
        curse_of_vanishing: "Maldición de Desaparición",
        density: "Densidad",
        breach: "Brecha",
        wind_burst: "Ráfaga de Viento",
        // Categories
        armor: "Armadura",
        weapons: "Armas",
        tools: "Herramientas",
        ranged: "A Distancia",
        trident: "Tridente",
        fishing: "Pesca",
        // Commands
        cmd_title: "§9[ §bConsola de Comandos §9]",
        cmd_label: "§bEscribe el comando (sin el /):",
        cmd_placeholder: "Ej: give @s diamond 64",
        cmd_sent: "Comando ejecutado",
        // Enchantments UI
        ench_pick: "§bEncantamiento:",
        ench_next: "Siguiente",
        ench_level: "§bNivel:",
        ench_buy: "Comprar",
        // TP messages
        tp_title_to: "§9[ §bTP / Coordenadas §9]",
        tp_title_here: "§9[ §bTraer Jugador §9]",
        tp_pick_player: "§bJugador objetivo:",
        tp_coords_field: "§bCoordenadas opcionales (X Y Z)",
        tp_coords_hint: "Ej: 100 64 -200",
        tp_coords_travel: "TP listo",
        tp_coords_err: "Error coordenadas",
        tp_no_players: "Sin jugadores.",
        tp_req_sent: "Solicitud enviada",
        tp_req_expire: "",
        tp_req_to: "IR",
        tp_req_here: "TRAER",
        tp_req_msg: "Solicitud TP:",
        tp_req_open: "Menu CDR → TP para aceptar.",
        tp_offline: "Desconectado.",
        tp_arrived: "TP ✔",
        tp_came: "Llegó.",
        tp_brought: "Llegó.",
        // Dimension blocking
        dim_btn: "§9[ §bDimensiones §9]",
        dim_global: "Bloqueo Global",
        dim_nether: "§9[ §bNether §9]",
        dim_end: "§9[ §bEnd §9]",
        dim_player: "Permisos Dimensiones",
        supremo_btn: "§9[ §bAdmin Supremo §9]",
        supremo_admind: "§9[ §bControl Admins §9]",
        supremo_free: "§bAdmins tienen todo gratis",
        supremo_wp_limit: "§bLímite de Marcadores (0 = sin límite)",
        admin_stats_edit_btn: "§9[ §bEditar Estadísticas §9]",
        admin_stats_edit_title: "§9[ §bEditor de Stats §9]",
        admin_stats_edit_desc: "Modifica los valores del jugador. Nota: El tiempo se guarda en ticks.",
        admin_priv_list_title: "§9[ §bLista de Admins §9]",
        admin_priv_btn: "§9[ §bPrivilegios §9]",
        admin_free_shop: "§bTienda Gratis",
        admin_inf_wps: "§bWaypoints Infinitos",
        admin_priv_desc: "Configuración de privilegios para el administrador.",
        price_control_title: "§9[ §bControl de Precios §9]",
        price_items_normal: "Multiplicador Objetos (Normal)",
        price_items_cursed: "Multiplicador Objetos (Maldecido)",
        price_effects_normal: "Multiplicador Efectos (Normal)",
        price_effects_cursed: "Multiplicador Efectos (Maldecido)",
        price_kits_normal: "Multiplicador Kits (Normal)",
        price_kits_cursed: "Multiplicador Kits (Maldecido)",
        price_mult_hint: "Ej: 1.0 (Sin cambio), 3.0 (Triple)",
        curses: "Maldiciones",
        cursed: "§5[ §bMaldecido §5]",
        cursed_money: "§9[ §bSaldo: §9] §5$",
        cursed_title: "§5[ §bSISTEMA MALDECIDO §5]",
        cursed_desc: "Has sido marcado por una maldición administrativa. Debes completar misiones muy difíciles para limpiarte.",
        cursed_price: "§cPrecio (D. Normal): §a$",
        cursed_price_alt: "§5Precio (D. Maldecido): §5$",
        choose_currency: "Elegir Moneda",
        normal_money: "§9[ §bSaldo: §9] §a$",
        penalty_active: "§cPenalización activa. Menu bloqueado.",
        penalty_time: "§cTiempo restante: ",
        mission_fake: "§7Esta misión parecía legítima, pero era falsa...",
        mission_step_fail: "§cEl sistema ha decidido que esta vez no avanzas.",
        mission_step_partial: "§eEl sistema te ha quitado menos de lo esperado.",
        safe_zone_blocked: "§cZona segura bloqueada por penalización.",
        cursed_cleared: "§9[§bCDR§9] §f¡Has limpiado tu maldición!",
        test_mode_btn: "§9[ §bPruebas §9]",
        test_mode_on: "§9[§bCDR§9] §fModo Pruebas activado. Las restricciones ahora te afectan.",
        test_mode_off: "§9[§bCDR§9] §fModo Pruebas desactivado. Privilegios restaurados.",
        // Mission Targets
        zombie: "Zombi", skeleton: "Esqueleto", spider: "Araña", creeper: "Creeper",
        pig: "Cerdo", cow: "Vaca", sheep: "Oveja", chicken: "Pollo",
        rabbit: "Conejo", squid: "Calamar", glow_squid: "Calamar Brillante", cod: "Bacalao",
        salmon: "Salmón", tropical_fish: "Pez Tropical", pufferfish: "Pez Globo", bee: "Abeja",
        fox: "Zorro", wolf: "Lobo", cat: "Gato", ocelot: "Ocelote",
        parrot: "Loro", turtle: "Tortuga", frog: "Rana", tadpole: "Renacuajo",
        bat: "Murciélago", goat: "Cabra", armadillo: "Armadillo", silverfish: "Lepisma",
        cave_spider: "Araña de Cueva", slime: "Slime", strider: "Lavagante", villager: "Aldeano",
        wandering_trader: "Vendedor Ambulante", donkey: "Burro", horse: "Caballo", mule: "Mula",
        skeleton_horse: "Caballo Esqueleto", zombie_horse: "Caballo Zombi", llama: "Llama", trader_llama: "Llama de Vendedor",
        panda: "Panda", polar_bear: "Oso Polar", snow_golem: "Gólem de Nieve", iron_golem: "Gólem de Hierro",
        axolotl: "Ajolote", allay: "Allay", sniffer: "Sniffer", camel: "Camello",
        mooshroom: "Champiñaca", enderman: "Enderman", drowned: "Ahogado", husk: "Zombie Desértico",
        stray: "Esqueleto Glacial", witch: "Bruja", phantom: "Phanton", pillager: "Saqueador",
        vindicator: "Vindicador", guardian: "Guardián", blaze: "Blaze", ghast: "Ghast",
        magma_cube: "Cubo de Magma", hoglin: "Hoglin", piglin: "Piglin", zombified_piglin: "Piglin Zombificado",
        shulker: "Shulker", endermite: "Endermite", vex: "Vex", breeze: "Brisa", bogged: "Bogged",
        zombie_villager: "Aldeano Zombi", illusioner: "Ilusionista", zoglin: "Zoglin", piglin_brute: "Piglin Bruto",
        evoker: "Invocador", ravager: "Devastador", elder_guardian: "Guardián Anciano", wither_skeleton: "Esqueleto Wither",
        warden: "Warden", ender_dragon: "Dragón del End", wither: "Wither",
        stone: "Piedra", dirt: "Tierra", grass_block: "Bloque de Hierba", cobblestone: "Adoquín",
        deepslate: "Pizarra Profunda", tuff: "Toba", calcite: "Calcita",
        gold_ore: "Mineral de Oro", iron_ore: "Mineral de Hierro", coal_ore: "Mineral de Carbón",
        copper_ore: "Mineral de Cobre", lapis_ore: "Mineral de Lapislázuli", redstone_ore: "Mineral de Redstone",
        emerald_ore: "Mineral de Esmeralda", diamond_ore: "Mineral de Diamante",
        ancient_debris: "Detritos Ancestrales", obsidian: "Obsidiana", crying_obsidian: "Obsidiana Llorosa",
        nether_gold_ore: "Mineral de Oro del Nether", nether_quartz_ore: "Mineral de Cuarzo del Nether",
        deepslate_gold_ore: "Mineral de Oro de Pizarra", deepslate_iron_ore: "Mineral de Hierro de Pizarra",
        deepslate_coal_ore: "Mineral de Carbón de Pizarra", deepslate_diamond_ore: "Mineral de Diamante de Pizarra",
        deepslate_emerald_ore: "Mineral de Esmeralda de Pizarra",
        raw_iron_block: "Bloque de Hierro Bruto", raw_gold_block: "Bloque de Oro Bruto", raw_copper_block: "Bloque de Cobre Bruto",
        oak_log: "Tronco de Roble", spruce_log: "Tronco de Abeto", birch_log: "Tronco de Abedul",
        jungle_log: "Tronco de Jungla", acacia_log: "Tronco de Acacia", dark_oak_log: "Tronco de Roble Oscuro",
        mangrove_log: "Tronco de Manglar", cherry_log: "Tronco de Cerezo",
        netherrack: "Piedra del Nether", soul_sand: "Arena de Almas", soul_soil: "Tierra de Almas",
        sculk: "Sculk", sculk_sensor: "Sensor de Sculk", sculk_shrieker: "Chirriador de Sculk", sculk_catalyst: "Catalizador de Sculk",
        amethyst_cluster: "Cúmulo de Amatista", amethyst_block: "Bloque de Amatista",
        sea_lantern: "Linterna del Mar", glowstone: "Piedra Luminosa",
        magma: "Bloque de Magma", ice: "Hielo", packed_ice: "Hielo Compacto", blue_ice: "Hielo Azul",
        pumpkin: "Calabaza", melon_block: "Sandía", cactus: "Cactus", bamboo: "Bambú",
        sugar_cane: "Caña de Azúcar", wheat: "Trigo", potatoes: "Patatas", carrots: "Zanahorias"
    },
    en: {
        main_title: "§9[ §bMENU CDR §9]",
        stats_btn: "§9[ §bStatistics §9]",
        lang_btn: "§9[ §bLanguages §9]",
        return_btn: "§c[ §6Return §c]",
        balance: "§9[ §bBalance: §9] §a$",
        balance_cursed: "§9[ §bBalance: §9] §5$",
        balance_blocked_msg: "(You cannot use this balance)",
        user_label: "§9[ §bUser: §9] §f",
        commands: "§9[ §bConsole §9]",
        tp: "§9[ §bTeleport §9]",
        tp_to: "§9[ §bTP §9]",
        tp_here: "§9[ §bBring Friend §9]",
        tp_accept: "§9[ §bAccept §9]",
        wp_go: "§9[ §bGo §9]",
        waypoint: "§9[ §bWaypoints §9]",
        shop: "§9[ §bShop §9]",
        shop_title: "§9[ §bShop §9]",
        effects: "§9[ §bEffects §9]",
        items: "§9[ §bItems §9]",
        enchantments: "§9[ §bEnchantments §9]",
        enchantments_title: "§9[ §bEnchantments §9]",
        kits: "§9[ §bKits §9]",
        money: "§9[ §bSend Money §9]",
        money_sent: "§aYou sent money to: §b",
        money_cooldown: "§cYou must wait 3 in-game days to send cursed money again.",
        money_infected: "§cYou have been infected by a curse from §b",
        missions: "§9[ §bMissions §9]",
        missions_title: "§9[ §bMissions §9]",
        board_updated: "Board updated",
        missions_mult: "§bMissions Multiplier",
        mission_easy: "§9[ §bEasy §9]",
        mission_normal: "§9[ §bNormal §9]",
        mission_hard: "§9[ §bHard §9]",
        mission_hardcore: "§9[ §bHardcore §9]",
        mission_your: "Your Mission",
        mission_task: "Task",
        mission_obj: "Objective",
        mission_prog: "Progress",
        mission_reward: "Approx Reward",
        mission_renew: "Board renews in",
        mission_accept: "§9[ §bAccept Mission §9]",
        mission_cancel: "§9[ §bCancel Mission §9]",
        mission_abandon: "§c[ §fAbandon Failed §c]",
        mission_active: "§aACTIVE",
        mission_failed: "§cFAILED",
        mission_days: "Days",
        mission_kill: "Kill",
        mission_mine: "Mine",
        nether: "§9[ §bNether §9]",
        end: "§9[ §bEnd §9]",
        admin: "§9[ §bAdmin §9]",
        credits: "§9[ §bCredits §9]",
        stats_title: "§9[ §bStatistics §9]",
        stats: "§9[ §bStatistics §9]",
        sel_player: "§bSelect Player",
        stat_balance: "§9[ §bBalance §9]",
        stat_kill: "§9[ §bKills §9]",
        stat_deaths: "§9[ §bDeaths §9]",
        stat_mobs_passive: "§9[ §bPassive Mobs §9]",
        stat_mobs_hostile: "§9[ §bHostile Mobs §9]",
        stat_mobs_boss: "§9[ §bBosses §9]",
        stat_blocks: "§9[ §bBlocks §9]",
        stat_mission_easy: "§9[ §bEasy Mission §9]",
        stat_mission_normal: "§9[ §bNormal Mission §9]",
        stat_mission_hard: "§9[ §bHard Mission §9]",
        stat_mission_hardcore: "§9[ §bHardcore Mission §9]",
        stat_days: "§9[ §bDays Played §9]",
        stat_hours: "§9[ §bTime Played §9]",
        lang_title: "§9[ §bSelect Language §9]",
        lang_es: "§bEspañol",
        lang_en: "§bEnglish",
        lang_pt: "§bPortuguês",
        confirm: "§bConfirm",
        cancel: "§bCancel",
        success: "§aSuccess",
        error: "§cError",
        dimension_blocked_msg: "§cYou are not allowed to go to this dimension.",
        kit_iron: "§bIron Kit",
        kit_diamond: "§bDiamond Kit",
        kit_netherite: "§bNetherite Kit",
        moderation_title: "§9[ §bModeration §9]",
        vis_btn: "§9[ §bVisibility §9]",
        order_btn: "§9[ §bOrder §9]",
        diff_btn: "§9[ §bDifficulty §9]",
        gm_btn: "§9[ §bGame Mode §9]",
        econ_btn: "§9[ §bEconomy §9]",
        prices_btn: "§9[ §bPrices §9]",
        buy_btn: "§9[ §bGive money §9]",
        sell_btn: "§9[ §bRemove money §9]",
        remove_curse_btn: "§9[ §bRemove Curse §9]",
        add_curse_btn: "§9[ §bAdd Curse §9]",
        victim_label: "§bSelect Victim",
        guilty_label: "§bSelect Guilty",
        cursed: "§5[ §dCursed §5]",
        price_control_title: "§9[ §bPrice Control §9]",
        price_mult_hint: "Mult. (Ex: 1.0)",
        rew_passive: "§bPassive Reward",
        rew_hostile: "§bHostile Reward",
        rew_boss: "§bBoss Reward",
        pos_label: "Position",
        config_saved: "Config saved",
        order_saved: "Order saved",
        edit_player: "Edit Player",
        vis_global_desc: "Hide Global",
        perm_updated: "Permissions updated",
        all_players: "All (@a)",
        money_add: "Add Money",
        money_remove: "Remove Money",
        diff_p: "§a[ §bPeaceful §a]",
        diff_e: "§e[ §bEasy §e]",
        diff_n: "§6[ §bNormal §6]",
        diff_h: "§c[ §bHard §c]",
        gm_s: "§b[ §bSurvival §b]",
        gm_c: "§b[ §bCreative §b]",
        gm_a: "§b[ §bAdventure §b]",
        gm_sp: "§b[ §bSpectator §b]",
        wp_create_desc: "Enter name:",
        wp_saved_msg: "Waypoint saved",
        admin_msg: "§aAdmin Assigned",
        no_players: "No players",
        limit_reached: "Limit reached",
        helper_btn: "§9[ §bHelper §9]",
        rank_mgmt_btn: "§9[ §bRank Management §9]",
        rank_sel: "Select Rank",
        rank_admin: "Administrator (Full control)",
        rank_helper: "Helper (Basic moderation)",
        rank_none: "Remove Rank",
        rank_confirm_title: "Confirm Rank",
        rank_confirm_body: "Are you sure?",
        rank_desc_admin: "Full access to commands and economy.",
        rank_desc_helper: "Access to basic moderation.",
        rank_desc_none: "No privileges.",
        rank_desc_cdr: "OWNER (CDR). Absolute control.",
        wp_infinite: "Infinite Waypoints",
        test_mode_title: "§9[ §bTest Panel §9]",
        test_mode_player: "§bTest as Player",
        test_mode_helper: "§bTest as Helper",
        test_mode_admin: "§bTest as Administrator",
        test_mode_reset: "§cDisable modes",
        test_mode_on: "Test Mode activated.",
        test_mode_off: "Test Mode deactivated.",
        test_mode_helper_active: "Test Mode: HELPER activated.",
        test_mode_admin_active: "Test Mode: ADMINISTRATOR activated.",
        only_one_at_time: "Only one at a time",
        credits_body: "§8§l»-----------------------«\n§9§l   CDR SYSTEMS v2.0\n§8§l»-----------------------«\n§bCreated by:\n§f- §6ARSENIC 2007 §7(Dev)\n§f- §eREYES200705 §7(UI)\n\n§bModules:\n§f- §7Menu Engine\n§f- §7Rank Manager\n\n§8§l»-----------------------«\n§7 Thanks for your trust\n§8§l»-----------------------«",
        active: "Active",
        busy: "Busy",
        warning_curse_clear: "WARNING! Completing any will clear your curse.",
        progreso_actualizado: "Progress updated",
        maldicion_removida: "Curse removed!",
        mission_title_cursed: "§9[ §5CURSED SYSTEM §9]",
        mission_label: "Mission",
        admin_control_label: "(CDR/ADM/HELP)",
        ow_short: "OW", net_short: "NET", end_short: "END",
        engine_loaded: "Menu Engine v1.0 - §aLOADED",
        perm_target_msg: "Your permissions have been updated.",
        // Enchantments
        protection: "Protection",
        fire_protection: "Fire Protection",
        feather_falling: "Feather Falling",
        blast_protection: "Blast Protection",
        projectile_protection: "Projectile Protection",
        respiration: "Respiration",
        aqua_affinity: "Aqua Affinity",
        thorns: "Thorns",
        depth_strider: "Depth Strider",
        frost_walker: "Frost Walker",
        soul_speed: "Soul Speed",
        swift_sneak: "Swift Sneak",
        sharpness: "Sharpness",
        smite: "Smite",
        bane_of_arthropods: "Bane of Arthropods",
        knockback: "Knockback",
        fire_aspect: "Fire Aspect",
        looting: "Looting",
        efficiency: "Efficiency",
        silk_touch: "Silk Touch",
        unbreaking: "Unbreaking",
        fortune: "Fortune",
        power: "Power",
        punch: "Punch",
        flame: "Flame",
        infinity: "Infinity",
        luck_of_the_sea: "Luck of the Sea",
        lure: "Lure",
        loyalty: "Loyalty",
        impaling: "Impaling",
        riptide: "Riptide",
        channeling: "Channeling",
        multishot: "Multishot",
        piercing: "Piercing",
        quick_charge: "Quick Charge",
        mending: "Mending",
        curse_of_binding: "Curse of Binding",
        curse_of_vanishing: "Curse of Vanishing",
        density: "Density",
        breach: "Breach",
        wind_burst: "Wind Burst",
        // Categories
        armor: "Armor",
        weapons: "Weapons",
        tools: "Tools",
        ranged: "Ranged",
        trident: "Trident",
        fishing: "Fishing",
        // Commands
        cmd_title: "§9[ §bCommand Console §9]",
        cmd_label: "§bType the command (without /):",
        cmd_placeholder: "Ex: give @s diamond 64",
        cmd_sent: "Command executed",
        // Enchantments UI
        ench_pick: "§bEnchantment:",
        ench_next: "Next",
        ench_level: "§bLevel:",
        ench_buy: "Buy",
        // TP messages
        tp_title_to: "§9[ §bTP / Coordinates §9]",
        tp_title_here: "§9[ §bBring Player §9]",
        tp_pick_player: "§bTarget player:",
        tp_coords_field: "§bOptional coordinates (X Y Z)",
        tp_coords_hint: "Ex: 100 64 -200",
        tp_coords_travel: "TP done",
        tp_coords_err: "Coords error",
        tp_no_players: "No players.",
        tp_req_sent: "Request sent",
        tp_req_expire: "",
        tp_req_to: "GO",
        tp_req_here: "BRING",
        tp_req_msg: "TP request:",
        tp_req_open: "CDR Menu → TP to accept.",
        tp_offline: "Offline.",
        tp_arrived: "TP ✔",
        tp_came: "Arrived.",
        tp_brought: "Arrived.",
        // Dimension blocking
        dim_btn: "§9[ §bDimensions §9]",
        dim_global: "Global Block",
        dim_nether: "§9[ §bNether §9]",
        dim_end: "§9[ §bEnd §9]",
        dim_player: "Dimension Permissions",
        supremo_btn: "§9[ §bSupreme Admin §9]",
        supremo_admind: "§9[ §bAdmin Control §9]",
        supremo_free: "§bAdmins get everything free",
        supremo_wp_limit: "§bWaypoint Limit (0 = no limit)",
        admin_stats_edit_btn: "§9[ §bEdit Statistics §9]",
        admin_stats_edit_title: "§9[ §bStats Editor §9]",
        admin_stats_edit_desc: "Modify player values. Note: Time is saved in ticks.",
        admin_priv_list_title: "§9[ §bAdmin List §9]",
        admin_priv_btn: "§9[ §bPrivileges §9]",
        admin_free_shop: "§bFree Shop",
        admin_inf_wps: "§bInfinite Waypoints",
        admin_priv_desc: "Privilege configuration for this administrator.",
        price_control_title: "§9[ §bPrice Control §9]",
        price_items_normal: "Items Multiplier (Normal)",
        price_items_cursed: "Items Multiplier (Cursed)",
        price_effects_normal: "Effects Multiplier (Normal)",
        price_effects_cursed: "Effects Multiplier (Cursed)",
        price_kits_normal: "Kits Multiplier (Normal)",
        price_kits_cursed: "Kits Multiplier (Cursed)",
        price_mult_hint: "Ex: 1.0 (No change), 3.0 (Triple)",
        curses: "Curses",
        cursed: "§5[ §bCursed §5]",
        cursed_money: "§9[ §bBalance: §9] §5$",
        cursed_title: "§5[ §bCURSED SYSTEM §5]",
        cursed_desc: "You have been marked by an administrative curse. You must complete very difficult missions to clear yourself.",
        cursed_price: "§cPrice (Normal M.): §a$",
        cursed_price_alt: "§5Price (Cursed M.): §5$",
        choose_currency: "Choose Currency",
        normal_money: "Normal Money",
        penalty_active: "§cPenalty active. Menu blocked.",
        penalty_time: "§cTime remaining: ",
        mission_fake: "§7This mission seemed legitimate, but it was fake...",
        mission_step_fail: "§cThe system decided you won't progress this time.",
        mission_step_partial: "§eThe system took less than expected.",
        safe_zone_blocked: "§cSafe zone blocked by penalty.",
        cursed_cleared: "§9[§bCDR§9] §fAll your curse has been cleared!",
        // Mission Targets
        zombie: "Zombie", skeleton: "Skeleton", spider: "Spider", creeper: "Creeper",
        pig: "Pig", cow: "Cow", sheep: "Sheep", chicken: "Chicken",
        rabbit: "Rabbit", squid: "Squid", glow_squid: "Glow Squid", cod: "Cod",
        salmon: "Salmon", tropical_fish: "Tropical Fish", pufferfish: "Pufferfish", bee: "Bee",
        fox: "Fox", wolf: "Wolf", cat: "Cat", ocelot: "Ocelot",
        parrot: "Parrot", turtle: "Turtle", frog: "Frog", tadpole: "Tadpole",
        bat: "Bat", goat: "Goat", armadillo: "Armadillo", silverfish: "Silverfish",
        cave_spider: "Cave Spider", slime: "Slime", strider: "Strider", villager: "Villager",
        wandering_trader: "Wandering Trader", donkey: "Donkey", horse: "Horse", mule: "Mule",
        skeleton_horse: "Skeleton Horse", zombie_horse: "Zombie Horse", llama: "Llama", trader_llama: "Trader Llama",
        panda: "Panda", polar_bear: "Polar Bear", snow_golem: "Snow Golem", iron_golem: "Iron Golem",
        axolotl: "Axolotl", allay: "Allay", sniffer: "Sniffer", camel: "Camel",
        mooshroom: "Mooshroom", enderman: "Enderman", drowned: "Drowned", husk: "Husk",
        stray: "Stray", witch: "Witch", phantom: "Phantom", pillager: "Pillager",
        vindicator: "Vindicator", guardian: "Guardian", blaze: "Blaze", ghast: "Ghast",
        magma_cube: "Magma Cube", hoglin: "Hoglin", piglin: "Piglin", zombified_piglin: "Zombified Piglin",
        shulker: "Shulker", endermite: "Endermite", vex: "Vex", breeze: "Breeze", bogged: "Bogged",
        zombie_villager: "Zombie Villager", illusioner: "Illusioner", zoglin: "Zoglin", piglin_brute: "Piglin Brute",
        evoker: "Evoker", ravager: "Ravager", elder_guardian: "Elder Guardian", wither_skeleton: "Wither Skeleton",
        warden: "Warden", ender_dragon: "Ender Dragon", wither: "Wither",
        // Blocks
        stone: "Stone", dirt: "Dirt", grass_block: "Grass Block", cobblestone: "Cobblestone",
        sand: "Sand", gravel: "Gravel",
        oak_log: "Oak Log", spruce_log: "Spruce Log", birch_log: "Birch Log", jungle_log: "Jungle Log", acacia_log: "Acacia Log", dark_oak_log: "Dark Oak Log",
        mangrove_log: "Mangrove Log", cherry_log: "Cherry Log", oak_leaves: "Oak Leaves",
        deepslate: "Deepslate", tuff: "Tuff", calcite: "Calcite",
        gold_ore: "Gold Ore", iron_ore: "Iron Ore", coal_ore: "Coal Ore", copper_ore: "Copper Ore",
        lapis_ore: "Lapis Ore", redstone_ore: "Redstone Ore", emerald_ore: "Emerald Ore", diamond_ore: "Diamond Ore",
        ancient_debris: "Ancient Debris", obsidian: "Obsidian", crying_obsidian: "Crying Obsidian",
        raw_iron_block: "Raw Iron Block", raw_gold_block: "Raw Gold Block", raw_copper_block: "Raw Copper Block",
        netherrack: "Netherrack", soul_sand: "Soul Sand", soul_soil: "Soul Soil",
        sculk: "Sculk", sculk_sensor: "Sculk Sensor", sculk_shrieker: "Sculk Shrieker", sculk_catalyst: "Sculk Catalyst",
        amethyst_cluster: "Amethyst Cluster", amethyst_block: "Amethyst Block",
        sea_lantern: "Sea Lantern", glowstone: "Glowstone", magma: "Magma Block",
        ice: "Ice", packed_ice: "Packed Ice", blue_ice: "Blue Ice",
        pumpkin: "Pumpkin", melon_block: "Melon", cactus: "Cactus", bamboo: "Bamboo",
        sugar_cane: "Sugar Cane", wheat: "Wheat", potatoes: "Potatoes", carrots: "Carrots"
    },
    pt: {
        main_title: "§9[ §bMENU CDR §9]",
        stats_btn: "§9[ §bEstatísticas §9]",
        lang_btn: "§9[ §bIdiomas §9]",
        return_btn: "§c[ §6Voltar §c]",
        balance: "§9[ §bSaldo: §9] §a$",
        balance_cursed: "§9[ §bSaldo: §9] §5$",
        balance_blocked_msg: "(Você não pode usar este saldo)",
        user_label: "§9[ §bUsuário: §9] §f",
        commands: "§9[ §bConsole §9]",
        tp: "§9[ §bTeleporte §9]",
        waypoint: "§9[ §bMarcadores §9]",
        shop: "§9[ §bLoja §9]",
        shop_title: "§9[ §bLoja §9]",
        effects: "§9[ §bEfeitos §9]",
        items: "§9[ §bItens §9]",
        enchantments: "§9[ §bEncantamentos §9]",
        enchantments_title: "§9[ §bEncantamentos §9]",
        kits: "§9[ §bKits §9]",
        money: "§9[ §bEnviar Dinheiro §9]",
        money_sent: "§aVocê enviou dinheiro para: §b",
        money_cooldown: "§cVocê deve esperar 3 dias de jogo para enviar dinheiro amaldiçoado novamente.",
        money_infected: "§cVocê foi infectado por uma maldição de §b",
        missions: "§9[ §bMissões §9]",
        missions_title: "§9[ §bMissões §9]",
        board_updated: "Quadro atualizado",
        missions_mult: "§bMultiplicador Missões",
        mission_easy: "§9[ §bFácil §9]",
        mission_normal: "§9[ §bNormal §9]",
        mission_hard: "§9[ §bDifícil §9]",
        mission_hardcore: "§9[ §bHardcore §9]",
        mission_your: "Sua Missão",
        mission_task: "Tarefa",
        mission_obj: "Objetivo",
        mission_prog: "Progresso",
        mission_reward: "Recompensa aprox",
        mission_renew: "Quadro renova em",
        mission_accept: "§9[ §bAceitar Missão §9]",
        mission_cancel: "§9[ §bCancelar Missão §9]",
        mission_abandon: "§c[ §fAbandonar Falha §c]",
        mission_active: "§aATIVA",
        mission_failed: "§cFALHOU",
        mission_days: "Dias",
        mission_kill: "Matar",
        mission_mine: "Minar",
        nether: "§9[ §bNether §9]",
        end: "§9[ §bEnd §9]",
        admin: "§9[ §bAdministração §9]",
        credits: "§9[ §bCréditos §9]",
        stats_title: "§9[ §bEstatísticas §9]",
        stats: "§9[ §bEstatísticas §9]",
        sel_player: "§bEscolher Jogador",
        stat_balance: "§9[ §bSaldo §9]",
        stat_kill: "§9[ §bBajas §9]",
        stat_deaths: "§9[ §bMortes §9]",
        stat_mobs_passive: "§9[ §bMobs Passivos Derrotados §9]",
        stat_mobs_hostile: "§9[ §bMobs Hostis Derrotados §9]",
        stat_mobs_boss: "§9[ §bChefes Derrotados §9]",
        stat_blocks: "§9[ §bBlocos Quebrados §9]",
        stat_mission_easy: "§9[ §bMissão Fácil Concluída §9]",
        stat_mission_normal: "§9[ §bMissão Normal Concluída §9]",
        stat_mission_hard: "§9[ §bMissão Difícil Concluída §9]",
        stat_mission_hardcore: "§9[ §bMissão Hardcore Concluída §9]",
        stat_days: "§9[ §bDias Jogados §9]",
        stat_hours: "§9[ §bTempo Jogado §9]",
        lang_title: "§9[ §bEscolher Idioma §9]",
        lang_es: "§bEspañol",
        lang_en: "§bEnglish",
        lang_pt: "§bPortuguês",
        confirm: "§bConfirmar",
        cancel: "§bCancelar",
        success: "§aSucesso",
        error: "§cErro",
        dimension_blocked_msg: "§cVocê não tem permissão para ir a esta dimensão, fale com um administrador para entrar.",
        kit_iron: "§bKit Ferro",
        kit_diamond: "§bKit Diamante",
        kit_netherite: "§bKit Netherite",
        moderation_title: "§9[ §bModeração §9]",
        vis_btn: "§9[ §bVisibilidade §9]",
        order_btn: "§9[ §bOrdenar §9]",
        diff_btn: "§9[ §bDificuldade §9]",
        gm_btn: "§9[ §bModo Jogo §9]",
        econ_btn: "§9[ §bEconomia §9]",
        prices_btn: "§9[ §bPreços §9]",
        buy_btn: "§9[ §bDar dinheiro §9]",
        sell_btn: "§9[ §bTirar dinheiro §9]",
        remove_curse_btn: "§9[ §bRemover Maldição §9]",
        add_curse_btn: "§9[ §bAdicionar Maldição §9]",
        victim_label: "§bEscolher Vítima",
        guilty_label: "§bEscolher Culpado",
        cursed: "§5[ §dAmaldiçoado §5]",
        price_control_title: "§9[ §bPreços §9]",
        price_mult_hint: "Mult. (Ex: 1.0)",
        rew_passive: "§bRecompensa Passivos",
        rew_hostile: "§bRecompensa Hostis",
        rew_boss: "§bRecompensa Chefes",
        pos_label: "Posição",
        config_saved: "Configuração salva",
        order_saved: "Ordem salva",
        edit_player: "Editar Jogador",
        vis_global_desc: "Ocultar Global",
        perm_updated: "Permissões atualizadas",
        all_players: "Todos (@a)",
        money_add: "Dar Dinheiro",
        money_remove: "Tirar Dinheiro",
        diff_p: "§a[ §bPacífico §a]",
        diff_e: "§e[ §bFácil §e]",
        diff_n: "§6[ §bNormal §6]",
        diff_h: "§c[ §bDifícil §c]",
        gm_s: "§b[ §bSobrevivência §b]",
        gm_c: "§b[ §bCriativo §b]",
        gm_a: "§b[ §bAventura §b]",
        gm_sp: "§b[ §bEspectador §b]",
        wp_create_desc: "Digitar nome:",
        wp_saved_msg: "Marcador salvo",
        admin_msg: "§aAdmin Atribuído",
        no_players: "Sem jogadores",
        limit_reached: "Limite atingido",
        helper_btn: "§9[ §bAjudante §9]",
        rank_mgmt_btn: "§9[ §bGestão de Ranks §9]",
        rank_sel: "Selecionar Rank",
        rank_admin: "Administrador (Controle total)",
        rank_helper: "Ajudante (Moderação básica)",
        rank_none: "Remover Rank",
        rank_confirm_title: "Confirmar Rank",
        rank_confirm_body: "Tem certeza?",
        rank_desc_admin: "Acesso total a comandos e economia.",
        rank_desc_helper: "Acesso à moderação básica.",
        rank_desc_none: "Sem privilégios.",
        rank_desc_cdr: "PROPRIETÁRIO (CDR). Controle absoluto.",
        wp_infinite: "Waypoints Infinitos",
        test_mode_title: "§9[ §bPainel de Testes §9]",
        test_mode_player: "§bTestar como Jogador",
        test_mode_helper: "§bTestar como Ajudante",
        test_mode_admin: "§bTestar como Administrador",
        test_mode_reset: "§cDesactivar modos",
        test_mode_on: "Modo de Teste ativado.",
        test_mode_off: "Modo de Teste desativado.",
        test_mode_helper_active: "Modo de Teste: AJUDANTE ativado.",
        test_mode_admin_active: "Modo de Teste: ADMINISTRADOR ativado.",
        only_one_at_time: "Apenas um por vez",
        credits_body: "§8§l»-----------------------«\n§9§l   SISTEMAS CDR v2.0\n§8§l»-----------------------«\n§bCriado por:\n§f- §6ARSENIC 2007 §7(Dev)\n§f- §eREYES200705 §7(UI)\n\n§bModulos:\n§f- §7Menu Engine\n§f- §7Rank Manager\n\n§8§l»-----------------------«\n§7 Obrigado pela confiança\n§8§l»-----------------------«",
        active: "Ativa",
        busy: "Ocupado",
        warning_curse_clear: "AVISO! Completar qualquer uma limpará sua maldição.",
        progreso_actualizado: "Progresso atualizado",
        maldicion_removida: "Maldição removida!",
        mission_title_cursed: "§9[ §5SISTEMA AMALDIÇOADO §9]",
        mission_label: "Missão",
        admin_control_label: "(CDR/ADM/HELP)",
        ow_short: "SB", net_short: "NET", end_short: "END",
        engine_loaded: "Menu Engine v1.0 - §aCARREGADO",
        perm_target_msg: "Suas permissões foram atualizadas.",
        // Enchantments
        protection: "Proteção",
        fire_protection: "Proteção contra Fogo",
        feather_falling: "Peso de Pena",
        blast_protection: "Proteção contra Explosões",
        projectile_protection: "Proteção contra Projéteis",
        respiration: "Respiração",
        aqua_affinity: "Afinidade Aquática",
        thorns: "Espinhos",
        depth_strider: "Passos Profundos",
        frost_walker: "Caminhante de Geada",
        soul_speed: "Velocidade das Almas",
        swift_sneak: "Infiltrar com Velocidade",
        sharpness: "Afiação",
        smite: "Julgamento",
        bane_of_arthropods: "Ruína dos Artrópodes",
        knockback: "Repulsão",
        fire_aspect: "Aspecto de Fogo",
        looting: "Saque",
        efficiency: "Eficiência",
        silk_touch: "Toque de Seda",
        unbreaking: "Inquebrável",
        fortune: "Fortuna",
        power: "Força",
        punch: "Impacto",
        flame: "Chama",
        infinity: "Infinidade",
        luck_of_the_sea: "Sorte no Mar",
        lure: "Fisga",
        loyalty: "Lealdade",
        impaling: "Empalamento",
        riptide: "Correnteza",
        channeling: "Canalização",
        multishot: "Tiro Múltiplo",
        piercing: "Perfurante",
        quick_charge: "Carga Rápida",
        mending: "Remendo",
        curse_of_binding: "Maldição da Ligação",
        curse_of_vanishing: "Maldição do Desaparecimento",
        density: "Densidade",
        breach: "Fenda",
        wind_burst: "Explosão de Vento",
        // Categories
        armor: "Armadura",
        weapons: "Armas",
        tools: "Ferramentas",
        ranged: "A Distância",
        trident: "Tridente",
        fishing: "Pesca",
        // Commands
        cmd_title: "§9[ §bConsole de Comandos §9]",
        cmd_label: "§bDigite o comando (sem o /):",
        cmd_placeholder: "Ex: give @s diamond 64",
        cmd_sent: "Comando executado",
        // Enchantments UI
        ench_pick: "§bEncantamento:",
        ench_next: "Próximo",
        ench_level: "§bNível:",
        ench_buy: "Comprar",
        // TP messages
        tp_title_to: "§b[ §fTP / Coordenadas §b]",
        tp_title_here: "§b[ §fTrazer Jogador §b]",
        tp_pick_player: "§bJogador alvo:",
        tp_coords_field: "§bCoordenadas opcionais (X Y Z)",
        tp_coords_hint: "Ex: 100 64 -200",
        tp_coords_travel: "TP feito",
        tp_coords_err: "Erro coordenadas",
        tp_no_players: "Sem jogadores.",
        tp_req_sent: "Solicitude enviada",
        tp_req_expire: "",
        tp_req_to: "IR",
        tp_req_here: "TRAZER",
        tp_req_msg: "Pedido TP:",
        tp_req_open: "Menu CDR → TP para aceitar.",
        tp_offline: "Desconectado.",
        tp_arrived: "TP ✔",
        tp_came: "Chegou.",
        tp_brought: "Chegou.",
        // Dimension blocking
        dim_btn: "§9[ §bDimensões §9]",
        dim_global: "Bloqueio Global",
        dim_nether: "§9[ §bNether §9]",
        dim_end: "§9[ §bEnd §9]",
        dim_player: "Permissões Dimensões",
        supremo_btn: "§9[ §bAdmin Supremo §9]",
        supremo_admind: "§9[ §bControle Admins §9]",
        supremo_free: "§bAdmins têm tudo grátis",
        supremo_wp_limit: "§bLimite de Marcadores (0 = sem limite)",
        admin_stats_edit_btn: "§9[ §bEditar Estatísticas §9]",
        admin_stats_edit_title: "§9[ §bEditor de Stats §9]",
        admin_stats_edit_desc: "Modifique os valores do jogador. Nota: O tempo é salvo em ticks.",
        admin_priv_list_title: "§9[ §bLista de Admins §9]",
        admin_priv_btn: "§9[ §bPrivilégios §9]",
        admin_free_shop: "§bLoja Grátis",
        admin_inf_wps: "§bWaypoints Infinitos",
        admin_priv_desc: "Configuração de privilégios para o administrador.",
        price_items_normal: "Multiplicador de Itens (Normal)",
        price_items_cursed: "Multiplicador de Itens (Amaldiçoado)",
        price_effects_normal: "Multiplicador de Efeitos (Normal)",
        price_effects_cursed: "Multiplicador de Efeitos (Amaldiçoado)",
        price_kits_normal: "Multiplicador de Kits (Normal)",
        price_kits_cursed: "Multiplicador de Kits (Amaldiçoado)",
        curses: "Maldições",
        cursed_money: "§9[ §bSaldo: §9] §5$",
        cursed_title: "§5[ §bSISTEMA MALDECIDO §5]",
        cursed_desc: "Você foi marcado pela maldição administrativa. Deve completar missões para limpar sua tag.",
        cursed_price: "§cPreço (D. Normal): §a$",
        cursed_price_alt: "§5Preço (D. Maldecido): §5$",
        choose_currency: "Escolher Moeda",
        normal_money: "Dinheiro Normal",
        penalty_active: "§cPenalização ativa. Menu bloqueado.",
        penalty_time: "§cTempo restante: ",
        mission_fake: "§7Esta missão parecia legítima, mas era falsa...",
        mission_step_fail: "§cO sistema decidió que desta vez você não avança.",
        mission_step_partial: "§eO sistema tirou menos do que o esperado.",
        safe_zone_blocked: "§cZona segura bloqueada por penalização.",
        cursed_cleared: "§9[§bCDR§9] §fVocê limpou toda a sua maldição!",
        // Mission Targets
        zombie: "Zumbi", skeleton: "Esqueleto", spider: "Aranha", creeper: "Creeper",
        pig: "Porco", cow: "Vaca", sheep: "Ovelha", chicken: "Galinha",
        rabbit: "Coelho", squid: "Lula", glow_squid: "Lula Brilhante", cod: "Bacalhau",
        salmon: "Salmão", tropical_fish: "Peixe Tropical", pufferfish: "Peixe-balão", bee: "Abelha",
        fox: "Raposa", wolf: "Lobo", cat: "Gato", ocelot: "Jaguatirica",
        parrot: "Papagaio", turtle: "Tartaruga", frog: "Rã", tadpole: "Girino",
        bat: "Morcego", goat: "Cabra", armadillo: "Tatu", silverfish: "Peixinho-de-prata",
        cave_spider: "Aranha de Caverna", slime: "Slime", strider: "Lavagante", villager: "Aldeão",
        wandering_trader: "Vendedor Ambulante", donkey: "Burro", horse: "Cavalo", mule: "Mula",
        skeleton_horse: "Cavalo Esqueleto", zombie_horse: "Cavalo Zumbi", llama: "Lhama", trader_llama: "Lhama de Vendedor",
        panda: "Panda", polar_bear: "Urso Polar", snow_golem: "Golem de Neve", iron_golem: "Golem de Ferro",
        axolotl: "Axolote", allay: "Allay", sniffer: "Sniffer", camel: "Camelo",
        mooshroom: "Champivaca", enderman: "Enderman", drowned: "Afogado", husk: "Husk",
        stray: "Stray", witch: "Bruxa", phantom: "Phantom", pillager: "Saqueador",
        vindicator: "Vindicador", guardian: "Guardião", blaze: "Blaze", ghast: "Ghast",
        magma_cube: "Cubo de Magma", hoglin: "Hoglin", piglin: "Piglin", zombified_piglin: "Piglin Zumbificado",
        shulker: "Shulker", endermite: "Endermite", vex: "Vex", breeze: "Brisa", bogged: "Bogged",
        zombie_villager: "Aldeão Zumbi", illusioner: "Ilusionista", zoglin: "Zoglin", piglin_brute: "Piglin Bruto",
        evoker: "Invocador", ravager: "Devastador", elder_guardian: "Guardião Ancião", wither_skeleton: "Esqueleto Wither",
        warden: "Warden", ender_dragon: "Dragão do End", wither: "Wither",
        // Blocks
        stone: "Pedra", dirt: "Terra", grass_block: "Bloco de Grama", cobblestone: "Pedregulho",
        sand: "Areia", gravel: "Cascalho",
        oak_log: "Tronco de Carvalho", spruce_log: "Tronco de Pinheiro", birch_log: "Tronco de Bétula", jungle_log: "Tronco de Selva", acacia_log: "Tronco de Acácia", dark_oak_log: "Tronco de Carvalho Escuro",
        mangrove_log: "Tronco de Mangue", cherry_log: "Tronco de Cerejeira", oak_leaves: "Folhas de Carvalho",
        deepslate: "Ardosia", tuff: "Tufo", calcite: "Calcita",
        gold_ore: "Minério de Ouro", iron_ore: "Minério de Ferro", coal_ore: "Minério de Carvão",
        copper_ore: "Minério de Cobre", lapis_ore: "Minério de Lápis-lazúli", redstone_ore: "Minério de Redstone",
        emerald_ore: "Minério de Esmeralda", diamond_ore: "Minério de Diamante",
        ancient_debris: "Detritos Ancestrais", obsidian: "Obsidiana", crying_obsidian: "Obsidiana Chorosa",
        raw_iron_block: "Bloco de Ferro Bruto", raw_gold_block: "Bloco de Ouro Bruto", raw_copper_block: "Bloco de Cobre Bruto",
        netherrack: "Pedra do Nether", soul_sand: "Areia das Almas", soul_soil: "Solo das Almas",
        sculk: "Sculk", sculk_sensor: "Sensor de Sculk", sculk_shrieker: "Chirriador de Sculk", sculk_catalyst: "Catalisador de Sculk",
        amethyst_cluster: "Aglomerado de Ametista", amethyst_block: "Bloco de Ametista",
        sea_lantern: "Lanterna Marinha", glowstone: "Pedra Luminosa", magma: "Bloco de Magma",
        ice: "Gelo", packed_ice: "Gelo Compacto", blue_ice: "Gelo Azul",
        pumpkin: "Abóbora", melon_block: "Melancia", cactus: "Cacto", bamboo: "Bambu",
        sugar_cane: "Cana-de-açúcar", wheat: "Trigo", potatoes: "Batatas", carrots: "Cenouras"
    }
};

export function t(player, key) {
    try {
        const lang = player.getDynamicProperty("cdr_lang") ?? "es";
        const dict = LANG[lang] ?? LANG["es"];
        return dict[key] ?? key;
    } catch (e) {
        return key;
    }
}

export function playSoundAndNotify(player, message) {
    player.sendMessage(`§9[§bCDR§9] §f${message}`);
    player.runCommandAsync(`playsound random.levelup @s ~ ~ ~ 1 1`).catch(() => { });
}
